name: CD - Build & Migrate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start DB container
        run: docker compose up -d db

      - name: Wait for DB to be ready
        run: sleep 10

      - name: Run DB migrations
        run: docker compose run --rm migrate


  build-app:
    runs-on: ubuntu-latest
    needs: migrate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build App Container
        run: docker compose build app
