name: CD - Build & Migrate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - uses: docker/setup-buildx-action@v3

      - name: Build app with bake
        env:
          COMPOSE_BAKE: true
        run: docker compose build app

      - name: Start DB container
        run: docker compose up -d db

      - name: Wait for DB ready
        run: sleep 10

      - name: Run DB migrations
        run: docker compose up migrate

      - name: Shut down DB container
        run: docker compose down
